---
- name: Add a user on Ubuntu and CentOS instances
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Add a user
    user:
      name: "{{ morpheus['customOptions']['username'] }}"
      password: "{{ lookup('cypher','secret=secret/userpass') | password_hash('sha512') }}"
      state: present
    when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "CentOS")
